
import type { Bible } from '@/lib/types';

export const emtv: Bible = [
  {
    book: 'Genesis',
    chapters: [
      {
        chapter: 1,
        verses: [
          { verse: 1, text: 'In the beginning God created the heavens and the earth.' },
          { verse: 2, text: 'Now the earth was formless and empty, and darkness was over the surface of the deep. And the Spirit of God was hovering over the surface of the waters.' },
          { verse: 3, text: 'And God said, "Let there be light," and there was light.' },
          { verse: 4, text: 'And God saw that the light was good, and God separated the light from the darkness.' },
          { verse: 5, text: 'God called the light "day," and the darkness He called "night." And there was evening, and there was morning--the first day.' },
        ],
      },
    ],
  },
  { book: 'Exodus', chapters: [] },
  { book: 'Leviticus', chapters: [] },
  { book: 'Numbers', chapters: [] },
  { book: 'Deuteronomy', chapters: [] },
  { book: 'Joshua', chapters: [] },
  { book: 'Judges', chapters: [] },
  { book: 'Ruth', chapters: [] },
  { book: '1 Samuel', chapters: [] },
  { book: '2 Samuel', chapters: [] },
  { book: '1 Kings', chapters: [] },
  { book: '2 Kings', chapters: [] },
  { book: '1 Chronicles', chapters: [] },
  { book: '2 Chronicles', chapters: [] },
  { book: 'Ezra', chapters: [] },
  { book: 'Nehemiah', chapters: [] },
  { book: 'Esther', chapters: [] },
  { book: 'Job', chapters: [] },
  { book: 'Psalms', chapters: [] },
  { book: 'Proverbs', chapters: [] },
  { book: 'Ecclesiastes', chapters: [] },
  { book: 'Song of Solomon', chapters: [] },
  { book: 'Isaiah', chapters: [] },
  { book: 'Jeremiah', chapters: [] },
  { book: 'Lamentations', chapters: [] },
  { book: 'Ezekiel', chapters: [] },
  { book: 'Daniel', chapters: [] },
  { book: 'Hosea', chapters: [] },
  { book: 'Joel', chapters: [] },
  { book: 'Amos', chapters: [] },
  { book: 'Obadiah', chapters: [] },
  { book: 'Jonah', chapters: [] },
  { book: 'Micah', chapters: [] },
  { book: 'Nahum', chapters: [] },
  { book: 'Habakkuk', chapters: [] },
  { book: 'Zephaniah', chapters: [] },
  { book: 'Haggai', chapters: [] },
  { book: 'Zechariah', chapters: [] },
  { book: 'Malachi', chapters: [] },
  { book: 'Matthew', chapters: [] },
  { book: 'Mark', chapters: [] },
  { book: 'Luke', chapters: [] },
  { book: 'John', chapters: [] },
  { book: 'Acts', chapters: [] },
  { book: 'Romans', chapters: [] },
  { book: '1 Corinthians', chapters: [] },
  { book: '2 Corinthians', chapters: [] },
  { book: 'Galatians', chapters: [] },
  { book: 'Ephesians', chapters: [] },
  { book: 'Philippians', chapters: [] },
  { book: 'Colossians', chapters: [] },
  { book: '1 Thessalonians', chapters: [] },
  { book: '2 Thessalonians', chapters: [] },
  { book: '1 Timothy', chapters: [] },
  { book: '2 Timothy', chapters: [] },
  { book: 'Titus', chapters: [] },
  { book: 'Philemon', chapters: [] },
  { book: 'Hebrews', chapters: [] },
  { book: 'James', chapters: [] },
  { book: '1 Peter', chapters: [] },
  { book: '2 Peter', chapters: [] },
  { book: '1 John', chapters: [] },
  { book: '2 John', chapters: [] },
  { book: '3 John', chapters: [] },
  { book: 'Jude', chapters: [] },
  { book: 'Revelation', chapters: [] },
];
