import type { Bible } from '@/lib/types';

export const kjv: Bible = [
    { book: 'Genesis', chapterCount: 50 },
    { book: 'Exodus', chapterCount: 40 },
    { book: 'Leviticus', chapterCount: 27 },
    { book: 'Numbers', chapterCount: 36 },
    { book: 'Deuteronomy', chapterCount: 34 },
    { book: 'Joshua', chapterCount: 24 },
    { book: 'Judges', chapterCount: 21 },
    { book: 'Ruth', chapterCount: 4 },
    { book: '1 Samuel', chapterCount: 31 },
    { book: '2 Samuel', chapterCount: 24 },
    { book: '1 Kings', chapterCount: 22 },
    { book: '2 Kings', chapterCount: 25 },
    { book: '1 Chronicles', chapterCount: 29 },
    { book: '2 Chronicles', chapterCount: 36 },
    { book: 'Ezra', chapterCount: 10 },
    { book: 'Nehemiah', chapterCount: 13 },
    { book: 'Esther', chapterCount: 10 },
    { book: 'Job', chapterCount: 42 },
    { book: 'Psalms', chapterCount: 150 },
    { book: 'Proverbs', chapterCount: 31 },
    { book: 'Ecclesiastes', chapterCount: 12 },
    { book: 'Song of Solomon', chapterCount: 8 },
    { book: 'Isaiah', chapterCount: 66 },
    { book: 'Jeremiah', chapterCount: 52 },
    { book: 'Lamentations', chapterCount: 5 },
    { book: 'Ezekiel', chapterCount: 48 },
    { book: 'Daniel', chapterCount: 12 },
    { book: 'Hosea', chapterCount: 14 },
    { book: 'Joel', chapterCount: 3 },
    { book: 'Amos', chapterCount: 9 },
    { book: 'Obadiah', chapterCount: 1 },
    { book: 'Jonah', chapterCount: 4 },
    { book: 'Micah', chapterCount: 7 },
    { book: 'Nahum', chapterCount: 3 },
    { book: 'Habakkuk', chapterCount: 3 },
    { book: 'Zephaniah', chapterCount: 3 },
    { book: 'Haggai', chapterCount: 2 },
    { book: 'Zechariah', chapterCount: 14 },
    { book: 'Malachi', chapterCount: 4 },
    { book: 'Matthew', chapterCount: 28 },
    { book: 'Mark', chapterCount: 16 },
    { book: 'Luke', chapterCount: 24 },
    { book: 'John', chapterCount: 21 },
    { book: 'Acts', chapterCount: 28 },
    { book: 'Romans', chapterCount: 16 },
    { book: '1 Corinthians', chapterCount: 16 },
    { book: '2 Corinthians', chapterCount: 13 },
    { book: 'Galatians', chapterCount: 6 },
    { book: 'Ephesians', chapterCount: 6 },
    { book: 'Philippians', chapterCount: 4 },
    { book: 'Colossians', chapterCount: 4 },
    { book: '1 Thessalonians', chapterCount: 5 },
    { book: '2 Thessalonians', chapterCount: 3 },
    { book: '1 Timothy', chapterCount: 6 },
    { book: '2 Timothy', chapterCount: 4 },
    { book: 'Titus', chapterCount: 3 },
    { book: 'Philemon', chapterCount: 1 },
    { book: 'Hebrews', chapterCount: 13 },
    { book: 'James', chapterCount: 5 },
    { book: '1 Peter', chapterCount: 5 },
    { book: '2 Peter', chapterCount: 3 },
    { book: '1 John', chapterCount: 5 },
    { book: '2 John', chapterCount: 1 },
    { book: '3 John', chapterCount: 1 },
    { book: 'Jude', chapterCount: 1 },
    { book: 'Revelation', chapterCount: 22 },
];
